# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-19 05:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Alphabo_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='nickname',
            new_name='email',
        ),
    ]
