# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-22 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alphabo_app', '0002_auto_20160719_0535'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Time',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='lose',
            new_name='exit_time',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='device_id',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='draw',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='win',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='install_time',
            field=models.IntegerField(default=0),
        ),
    ]
