# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-22 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alphabo_app', '0003_auto_20160722_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='play_time',
            field=models.IntegerField(default=0),
        ),
    ]
