# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-22 16:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Alphabo_app', '0004_auto_20160722_1528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='last_time',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='play_time',
        ),
    ]
